### ISSUE TITLE
训练报错求助

### ISSUE THREAD

**Issue by kaiyu9991** [JoeNan1/MAD-YOLO#1]
您好！非常感谢您开源的代码
在训练您代码时报错：
  yolo.py的271行：for mi, s in zip(m.m, m.stride):
  报错AttributeError: 'Detect' object has no attribute 'm'   ，这里说m没有这个属性m，请问m.m代表什么呢？

**Comment by xiaohe6** [comment]
您好，我现在也是遇到了这个问题，请问您解决了嘛
